name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
    contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: impersonate
  PHP_VERSIONS: '["7.4"]'

jobs:
  semantic-git-messages:
    name: Commits
    uses: owncloud/reusable-workflows/.github/workflows/semantic-git-message.yml@work/semantic

  php-code-style:
    name: PHP Code Style
    uses: ./.github/workflows/php-codestyle.yml
    with:
      app-name: ${ env.APP_NAME }
      php-versions: ${ env.PHP_VERSIONS }

  php-unit:
    name: PHP Unit
    uses: ./.github/workflows/php-unit.yml
    with:
      app-name: ${ env.APP_NAME }
      php-versions: ${ env.PHP_VERSIONS }

