on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the app'
        required: true
        type: string
      php-versions:
        description: JSON array of PHP versions
        required: true
        type: string

jobs:
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}
        database: [sqlite]
        include:
          - php: "7.4"
            database: "mysql:8.0"

    services:
      mysql:
        image: ${{ startsWith(matrix.database,'mysql:') && matrix.database || '' }}
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: owncloud
        options: >-
          --health-cmd="mysqladmin ping -u root -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Install wait-for-it
        run: |
          mkdir -p $HOME/.local/bin
          ls -l $HOME/.local/bin
          curl -SsfL -o $HOME/.local/bin/wait-for "https://github.com/owncloud-ci/wait-for/releases/download/v2.0.7/wait-for-linux-amd64"
          chmod +x $HOME/.local/bin/wait-for
          curl -SsfL -o $HOME/.local/bin/wait-for-it "https://raw.githubusercontent.com/owncloud-docker/ubuntu/refs/heads/master/v22.04/overlay/usr/bin/wait-for-it"
          chmod +x $HOME/.local/bin/wait-for-it

      - name: Clone owncloud/core
        uses: actions/checkout@v4
        with:
          repository: owncloud/core

      - name: Checkout apps/${{ inputs.app-name }}
        uses: actions/checkout@v4
        with:
          path: apps/${{ inputs.app-name }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, gd, json, xml, zip
          ini-values: "memory_limit=1024M"

      - name: Install Composer dependencies
        run: |
          make install-composer-deps
          make vendor-bin-deps

      - name: Install Server
        env:
          DATA_DIRECTORY: ${{ github.workspace }}/data
          DB_TYPE: ${{ startsWith(matrix.database, 'mysql:') && 'mysql' || 'sqlite' }}
        run: |
          bash tests/drone/install-server.sh

      - name: Setup App
        run: |
          php occ a:e ${{ inputs.app-name }}

      - name: Run PHPUnit
        run: |
          cd apps/${{ inputs.app-name }}
          make test-php-unit

